# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


resources:
  repositories:
  - repository: AspNetWebApp   # identifier (no spaces allowed)
    type: github  # see below
    name: AspNetWebApp  # repository name (format depends on `type`)
    ref: master
    endpoint: RoopeshNair  # endpoint for a GitHub repository

pool:
  vmImage: 'Ubuntu 16.04'
variables:
  - name: foo2
    value: orange
  - group: Test
steps:
 - script: "echo $(foo2) $(var2)"
